export interface FBText {
  type: string
  version: string
  originX: string
  originY: string
  left: number
  top: number
  width: number
  height: number
  fill: string
  stroke: any
  strokeWidth: number
  strokeDashArray: any
  strokeLineCap: string
  strokeDashOffset: number
  strokeLineJoin: string
  strokeUniform: boolean
  strokeMiterLimit: number
  scaleX: number
  scaleY: number
  angle: number
  flipX: boolean
  flipY: boolean
  opacity: number
  shadow: any
  visible: boolean
  backgroundColor: string
  fillRule: string
  paintFirst: string
  globalCompositeOperation: string
  skewX: number
  skewY: number
  fontFamily: string
  fontWeight: string
  fontSize: number
  text: string
  underline: boolean
  overline: boolean
  linethrough: boolean
  textAlign: string
  fontStyle: string
  lineHeight: number
  textBackgroundColor: string
  charSpacing: number
  styles: any[]
  direction: string
  path: any
  pathStartOffset: number
  pathSide: string
  pathAlign: string
}
export interface FBImage {
  type: string
  version: string
  originX: string
  originY: string
  left: number
  top: number
  width: number
  height: number
  fill: string
  stroke: any
  strokeWidth: number
  strokeDashArray: any
  strokeLineCap: string
  strokeDashOffset: number
  strokeLineJoin: string
  strokeUniform: boolean
  strokeMiterLimit: number
  scaleX: number
  scaleY: number
  angle: number
  flipX: boolean
  flipY: boolean
  opacity: number
  shadow: any
  visible: boolean
  backgroundColor: string
  fillRule: string
  paintFirst: string
  globalCompositeOperation: string
  skewX: number
  skewY: number
  cropX: number
  cropY: number
  src: string
  crossOrigin: any
  filters: any[]
}

export interface PSDText {
  type: string
  version: string
  originX: string
  originY: string
  left: number
  top: number
  width: number
  height: number
  fill: string
  stroke: any
  strokeWidth: number
  strokeDashArray: any
  strokeLineCap: string
  strokeDashOffset: number
  strokeLineJoin: string
  strokeUniform: boolean
  strokeMiterLimit: number
  scaleX: number
  scaleY: number
  angle: number
  flipX: boolean
  flipY: boolean
  opacity: number
  shadow: any
  visible: boolean
  backgroundColor: string
  fillRule: string
  paintFirst: string
  globalCompositeOperation: string
  skewX: number
  skewY: number
  fontFamily: string
  fontWeight: string
  fontSize: number
  text: string
  underline: boolean
  overline: boolean
  linethrough: boolean
  textAlign: string
  fontStyle: string
  lineHeight: number
  textBackgroundColor: string
  charSpacing: number
  styles: any[]
  direction: string
  path: any
  pathStartOffset: number
  pathSide: string
  pathAlign: string
}
